### ISSUE TITLE
PixiJS license is removed??

### ISSUE THREAD

**Issue by Icemic** [ant-tinyjs/tinyjs-plugin-mesh#3]
Seems the code in this repo is taken from https://github.com/pixijs/pixi.js/blob/v4.x/src/mesh/

Why the copyright license is removed? It violates MIT License.

So do some other repos in ant-tinyjs group.

**Comment by Icemic** [comment]
.  wrong, edited

**Comment by yiiqii** [comment]
> Seems the code in this repo is taken from https://github.com/pixijs/pixi.js/blob/v4.x/src/mesh/
> 
> Why the copyright license is removed? It violates MIT License.
> 
> So do some other repos in ant-tinyjs group.

License and copyright notice will add in a few mouths
